locals {
  # ─── SUBSCRIPTION INFO ───────────────────────────────────────
  subscription_id       = data.azurerm_client_config.current.subscription_id
  subscription_id_short = substr(local.subscription_id, 0, 8)

  # ─── REGION SHORT CODES ──────────────────────────────────────
  region_short_codes = {
    "eastus"        = "eus"
    "eastus2"       = "eus2"
    "westus2"       = "wus2"
    "centralus"     = "cus"
    "westeurope"    = "weu"
    "northeurope"   = "neu"
    "southeastasia" = "sea"
  }
  region_short = lookup(local.region_short_codes, var.location, substr(var.location, 0, 4))

  # ═══════════════════════════════════════════════════════════════
  # ONE SUBSCRIPTION = ONE VAULT (ENFORCED)
  #
  # Instance number HARDCODED to "001"
  # Vault name is deterministic per subscription+env+region
  # Cannot accidentally create a second vault
  # ═══════════════════════════════════════════════════════════════

  key_vault_name      = "kv-${var.organization}-${var.environment}-${local.region_short}-001"
  resource_group_name = "rg-${var.organization}-${var.environment}-keyvault-${var.location}"

  # ─── STANDARD TAGS ───────────────────────────────────────────
  standard_tags = merge({
    Environment        = var.environment
    Organization       = var.organization
    ManagedBy          = "Terraform"
    Service            = "KeyVault"
    DataClassification = "Confidential"
    SubscriptionId     = local.subscription_id
    OneVaultPerSub     = "true"
  }, var.tags)

  # ─── SPLIT SECRETS ───────────────────────────────────────────
  auto_secrets = {
    for k, v in var.secrets_input : k => v if v.value == "AUTO_GENERATE"
  }
  manual_secrets = {
    for k, v in var.secrets_input : k => v if v.value != "AUTO_GENERATE"
  }

  # ═══════════════════════════════════════════════════════════════
  # TRANSFORM TO AVM MODULE FORMAT
  # ═══════════════════════════════════════════════════════════════

  # ─── KEYS → AVM FORMAT ──────────────────────────────────────
  module_keys = {
    for k, v in var.keys_input :
    "key-${var.organization}-${var.environment}-${k}" => {
      key_opts        = v.key_opts
      key_type        = v.key_type
      key_size        = v.key_size
      expiration_date = v.expiration_date
      rotation_policy = v.rotation_policy
      tags = merge(local.standard_tags, v.tags, {
        KeyPurpose = k
      })
    }
  }

  # ─── MANUAL SECRETS → AVM FORMAT ───────────────────────────
  module_manual_secrets = {
    for k, v in local.manual_secrets :
    "secret-${var.organization}-${var.environment}-${k}" => {
      name          = "secret-${var.organization}-${var.environment}-${k}"
      secret_string = v.value
      content_type  = v.content_type
      expiration_date = v.expiration_date
      tags = merge(local.standard_tags, v.tags, {
        SecretPurpose = k
        ContentType   = v.content_type
      })
    }
  }

  # ─── AUTO SECRETS → AVM FORMAT ─────────────────────────────
  module_auto_secrets = {
    for k, v in local.auto_secrets :
    "secret-${var.organization}-${var.environment}-${k}" => {
      name          = "secret-${var.organization}-${var.environment}-${k}"
      secret_string = random_password.generated[k].result
      content_type  = v.content_type
      expiration_date = v.expiration_date
      tags = merge(local.standard_tags, v.tags, {
        SecretPurpose = k
        ContentType   = v.content_type
        AutoGenerated = "true"
      })
    }
  }

  # ─── ALL SECRETS MERGED ─────────────────────────────────────
  module_secrets = merge(local.module_manual_secrets, local.module_auto_secrets)

  # ─── ROLE ASSIGNMENTS → AVM FORMAT ─────────────────────────
  module_role_assignments = merge(
    {
      for k, v in var.role_assignments : k => {
        role_definition_id_or_name = v.role_name
        principal_id               = v.principal_id
      }
    },
    var.enable_rbac_authorization ? {
      "terraform-deployer" = {
        role_definition_id_or_name = "Key Vault Administrator"
        principal_id               = data.azurerm_client_config.current.object_id
      }
    } : {}
  )

  # ─── PRIVATE ENDPOINTS → AVM FORMAT ────────────────────────
  module_private_endpoints = {
    for k, v in var.private_endpoints : k => {
      subnet_resource_id = v.subnet_id
      private_dns_zone_group = length(v.private_dns_zone_ids) > 0 ? {
        name                 = "pdz-${local.key_vault_name}"
        private_dns_zone_ids = v.private_dns_zone_ids
      } : null
      tags = local.standard_tags
    }
  }

  # ─── DIAGNOSTIC SETTINGS → AVM FORMAT ──────────────────────
  module_diagnostic_settings = var.enable_diagnostics && var.log_analytics_workspace_id != "" ? {
    "diag-${local.key_vault_name}" = {
      workspace_resource_id = var.log_analytics_workspace_id
    }
  } : {}

  # ─── LOCK → AVM FORMAT ─────────────────────────────────────
  module_lock = var.enable_lock ? {
    kind = "CanNotDelete"
    name = "lock-${local.key_vault_name}"
  } : null

  # ─── CONTACTS → AVM FORMAT ─────────────────────────────────
  module_contacts = {
    for email in var.contact_emails : email => {
      email = email
    }
  }

  # ─── NAME MAPS (for outputs) ───────────────────────────────
  key_name_map = {
    for k, v in var.keys_input :
    k => "key-${var.organization}-${var.environment}-${k}"
  }
  secret_name_map = {
    for k, v in var.secrets_input :
    k => "secret-${var.organization}-${var.environment}-${k}"
  }
}